/* DTVT Story OS V3
 * Integrates Story / Timeline / Story State / Canon Context / local Council
 * with the existing DTVT Canon IndexedDB. No API keys are stored here.
 */
(function(){
  "use strict";
  const DB_NAME="dtvt_story_os_v3_db", DB_VERSION=1;
  const STORES=["stories","chapters","timeline","proposals","reports"];
  const $=s=>document.querySelector(s);
  const esc=s=>{const d=document.createElement("div");d.textContent=s==null?"":String(s);return d.innerHTML};
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  const now=()=>new Date().toISOString();
  let currentStory=null,currentChapter=null;

  function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const db=e.target.result; STORES.forEach(s=>{if(!db.objectStoreNames.contains(s)){const st=db.createObjectStore(s,{keyPath:"id"});st.createIndex("storyId","storyId",{unique:false});}})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function all(store){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(store,"readonly").objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
  async function get(store,id){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(store,"readonly").objectStore(store).get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
  async function put(store,obj){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).put(obj);tx.oncomplete=()=>res(obj);tx.onerror=()=>rej(tx.error)})}
  async function bulk(store,items){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,"readwrite"),st=tx.objectStore(store);items.forEach(x=>st.put(x));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  async function remove(store,id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}

  function baseStory(){return {id:uid("story"),title:"Truyện mới",description:"",status:"DRAFT",canonVersion:"LIVE",createdAt:now(),updatedAt:now(),characters:[],canonRefs:[],chapters:[],timeline:[],state:{world:{},characters:{},relationships:{},organizations:{},power:{},knowledge:{}},settings:{}}}
  function baseChapter(story,number){return {id:uid("chapter"),storyId:story.id,number,title:`Chương ${number}`,status:"DRAFT",content:"",summary:"",canonRefs:[],characterRefs:[],locationRefs:[],timelineRef:null,storyStateBefore:structuredClone(story.state||{}),storyStateAfter:structuredClone(story.state||{}),createdAt:now(),updatedAt:now(),council:{status:"NOT_CHECKED",score:null,violations:[],warnings:[],checks:[],checkedAt:null}}}

  async function canonEntries(){try{return await DTVT_DB.all()}catch(e){console.warn("Canon DB unavailable",e);return[]}}
  async function canonById(id){try{return await DTVT_DB.get(id)}catch(e){return null}}
  async function canonContext(refs){const out=[];for(const id of refs||[]){const e=await canonById(id);if(e)out.push(e)}return out}

  function setMode(mode){["canon","story","timeline","council"].forEach(m=>{const b=$("#mode"+m[0].toUpperCase()+m.slice(1));if(b)b.classList.toggle("active",m===mode)});$("#canonWorkspace").classList.toggle("hidden",mode!=="canon");$("#storyWorkspace").classList.toggle("hidden",mode!=="story");$("#timelineWorkspace").classList.toggle("hidden",mode!=="timeline");$("#councilWorkspace").classList.toggle("hidden",mode!=="council");if(mode!=="canon")document.querySelector("#globalSearch").style.display="none";else document.querySelector("#globalSearch").style.display="";if(mode!=="canon")document.querySelector("#btnNew").style.display="none";else document.querySelector("#btnNew").style.display=""; if(mode==="story")renderStory(); if(mode==="timeline")renderTimeline(); if(mode==="council")renderCouncil();}

  async function renderStory(){
    const ws=$("#storyWorkspace"), stories=await all("stories");
    if(!currentStory && stories[0]) currentStory=stories[0];
    const chapters=currentStory?await all("chapters"):[];
    if(currentStory && currentChapter){currentChapter=chapters.find(c=>c.id===currentChapter.id)||null}
    const published=chapters.filter(c=>c.status==="PUBLISHED").length;
    ws.innerHTML=`<div class="so-shell"><div class="so-toolbar"><div><h2 class="so-title">📖 Story OS</h2><div class="so-sub">V3 · Canon-aware writing workspace</div></div><div class="actions"><button class="so-btn primary" id="soNewStory">+ Truyện</button><button class="so-btn" id="soExport">Xuất Story JSON</button><button class="so-btn" id="soImport">Nhập Story JSON</button><input id="soImportFile" type="file" accept="application/json" hidden></div></div>
    <div class="so-kpis"><div class="so-kpi"><strong>${stories.length}</strong><span>Dự án</span></div><div class="so-kpi"><strong>${chapters.length}</strong><span>Chương</span></div><div class="so-kpi"><strong>${published}</strong><span>Đã xuất bản</span></div><div class="so-kpi"><strong>${currentStory?esc(currentStory.status):"—"}</strong><span>Trạng thái</span></div></div>
    <div class="so-grid"><aside class="so-card so-sidebar"><div class="so-title">Dự án</div><div class="so-list">${stories.map(s=>`<div class="so-list-item ${currentStory&&s.id===currentStory.id?"active":""}" data-story="${s.id}">${esc(s.title)}<small>${esc(s.status)} · ${new Date(s.updatedAt).toLocaleString("vi-VN")}</small></div>`).join("")||`<div class="so-empty">Chưa có truyện.</div>`}</div></aside>
    <main class="so-main"><div id="soEditor"></div></main>
    <aside class="so-card so-right pad"><div class="so-title">Canon Context</div><div class="so-sub">Các mục Canon được chương tham chiếu.</div><div id="soContext" class="so-ref-list"></div><div class="so-divider"></div><div class="so-title">Story State</div><div class="so-sub">Trạng thái sau chương hiện tại.</div><pre id="soState" class="so-pre">{}</pre></aside></div></div>`;
    $("#soNewStory").onclick=()=>openStoryModal();$("#soExport").onclick=exportStory;$("#soImport").onclick=()=>$("#soImportFile").click();$("#soImportFile").onchange=e=>{if(e.target.files[0])importStory(e.target.files[0])};
    ws.querySelectorAll("[data-story]").forEach(el=>el.onclick=async()=>{currentStory=await get("stories",el.dataset.story);currentChapter=null;renderStory()});
    renderStoryEditor(chapters);
  }

  async function renderStoryEditor(chapters){
    const box=$("#soEditor");if(!currentStory){box.innerHTML=`<div class="so-card pad so-empty">Tạo một dự án truyện để bắt đầu.</div>`;return}
    if(!currentChapter && chapters.length) currentChapter=chapters.slice().sort((a,b)=>a.number-b.number)[chapters.length-1];
    const selected=currentChapter;
    const refs=selected?await canonContext(selected.canonRefs):[];
    $("#soContext").innerHTML=refs.map(e=>`<span class="so-chip so-ref" title="${esc(e.summary||"")}">${esc(e.id)} · ${esc(e.name)}</span>`).join("")||`<span class="so-muted so-small">Chưa tham chiếu Canon.</span>`;
    $("#soState").textContent=JSON.stringify(selected?selected.storyStateAfter:currentStory.state,null,2);
    box.innerHTML=`<div class="so-card pad"><div class="so-toolbar"><div><div class="so-title">${esc(currentStory.title)}</div><div class="so-sub">${esc(currentStory.description||"Chưa có mô tả")}</div></div><div class="actions"><button class="so-btn" id="soEditStory">Sửa truyện</button><button class="so-btn primary" id="soNewChapter">+ Chương</button></div></div><div class="so-two"><div class="so-form"><label>Chọn chương</label><select id="soChapterSelect">${chapters.map(c=>`<option value="${c.id}" ${selected&&c.id===selected.id?"selected":""}>${c.number}. ${esc(c.title)} — ${c.status}</option>`).join("")||`<option value="">Chưa có chương</option>`}</select></div><div class="so-form"><label>Trạng thái</label><div>${selected?`<span class="so-status ${selected.status}">${selected.status}</span>`:`—`}</div></div></div>${selected?`<div class="so-divider"></div><div class="so-form"><label>Tiêu đề chương</label><input id="soTitle" value="${esc(selected.title)}"/><label>Tóm tắt</label><textarea id="soSummary">${esc(selected.summary||"")}</textarea><label>Nội dung</label><textarea id="soContent" class="editor" placeholder="Viết chương tại đây...">${esc(selected.content||"")}</textarea><div class="so-two"><div><label>Canon IDs (mỗi dòng một ID)</label><textarea id="soCanonRefs" style="min-height:120px">${esc((selected.canonRefs||[]).join("\n"))}</textarea></div><div><label>Character IDs (mỗi dòng một ID)</label><textarea id="soCharRefs" style="min-height:120px">${esc((selected.characterRefs||[]).join("\n"))}</textarea></div></div><label>Story State sau chương (JSON)</label><textarea id="soStateAfter" style="min-height:220px">${esc(JSON.stringify(selected.storyStateAfter||currentStory.state,null,2))}</textarea><div class="so-toolbar"><div class="actions"><button class="so-btn" id="soSave">💾 Lưu nháp</button><button class="so-btn warn" id="soReady">Gửi kiểm tra</button><button class="so-btn ok" id="soPublish">Xuất bản</button></div><div class="actions"><button class="so-btn" id="soCheck">🔍 Kiểm Canon</button><button class="so-btn primary" id="soCouncil">🤖 Hội đồng</button></div></div><div id="soInlineReport"></div></div>`:`<div class="so-empty">Chưa có chương. Bấm “+ Chương”.</div>`}</div>`;
    if(selected){$("#soChapterSelect").onchange=async e=>{currentChapter=await get("chapters",e.target.value);renderStory()};$("#soEditStory").onclick=()=>openStoryModal(currentStory);$("#soNewChapter").onclick=()=>newChapter();$("#soSave").onclick=()=>saveChapter("DRAFT");$("#soReady").onclick=()=>saveChapter("READY_FOR_CHECK");$("#soPublish").onclick=()=>saveChapter("PUBLISHED");$("#soCheck").onclick=()=>runCouncil(false);$("#soCouncil").onclick=()=>runCouncil(true)}
    else {$("#soEditStory").onclick=()=>openStoryModal(currentStory);$("#soNewChapter").onclick=()=>newChapter()}
  }

  async function newChapter(){if(!currentStory)return;const chapters=await all("chapters");const number=chapters.filter(c=>c.storyId===currentStory.id).reduce((m,c)=>Math.max(m,c.number),0)+1;const c=baseChapter(currentStory,number);await put("chapters",c);currentChapter=c;currentStory.chapters=[...(currentStory.chapters||[]),c.id];currentStory.updatedAt=now();await put("stories",currentStory);renderStory()}
  async function saveChapter(status){if(!currentChapter)return;try{const c={...currentChapter,title:$("#soTitle").value.trim()||`Chương ${currentChapter.number}`,summary:$("#soSummary").value.trim(),content:$("#soContent").value,canonRefs:lines($("#soCanonRefs").value),characterRefs:lines($("#soCharRefs").value),storyStateAfter:JSON.parse($("#soStateAfter").value||"{}"),status,updatedAt:now()};const dup=(await all("chapters")).some(x=>x.storyId===c.storyId&&x.number===c.number&&x.id!==c.id);if(dup){alert("Trùng số chương trong cùng một truyện.");return}await put("chapters",c);currentChapter=c;currentStory.state=c.storyStateAfter;currentStory.updatedAt=now();await put("stories",currentStory);renderStory();if(status!=="DRAFT")alert(`Đã lưu: ${status}`)}catch(e){alert("Không thể lưu chương: "+e.message)}}
  const lines=s=>String(s||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean);

  async function runCouncil(announce){if(!currentChapter)return;const report=await validateChapter(currentChapter);currentChapter.council=report;currentChapter.updatedAt=now();await put("chapters",currentChapter);await put("reports",{id:uid("report"),chapterId:currentChapter.id,storyId:currentStory.id,createdAt:now(),...report});renderStory();if(announce)alert(report.status==="PASS"?"Hội đồng cục bộ: PASS — chưa có lỗi cấu trúc Canon rõ ràng.":"Hội đồng cục bộ: có vấn đề cần xem xét.")}
  async function validateChapter(c){const checks=[],violations=[],warnings=[];const canon=await canonEntries();const ids=new Set(canon.map(x=>x.id));(c.canonRefs||[]).forEach(id=>{if(ids.has(id))checks.push({name:`Canon ${id}`,status:"PASS",detail:"Canon ID tồn tại."});else{violations.push(`Canon ID không tồn tại: ${id}`);checks.push({name:`Canon ${id}`,status:"FAIL",detail:"Không tìm thấy trong Canon Database."})}});const chapters=await all("chapters");const dup=chapters.filter(x=>x.storyId===c.storyId&&x.number===c.number&&x.id!==c.id);if(dup.length){violations.push(`Trùng số chương: ${c.number}`);checks.push({name:"Chapter numbering",status:"FAIL",detail:"Số chương bị trùng."})}else checks.push({name:"Chapter numbering",status:"PASS",detail:"Không trùng số chương."});try{JSON.parse(JSON.stringify(c.storyStateAfter||{}));checks.push({name:"Story State",status:"PASS",detail:"Story State là JSON hợp lệ."})}catch(e){violations.push("Story State không hợp lệ");checks.push({name:"Story State",status:"FAIL",detail:e.message})}if(!c.content||c.content.trim().length<50){warnings.push("Nội dung chương đang rất ngắn hoặc trống.");checks.push({name:"Content completeness",status:"WARN",detail:"Nội dung dưới ngưỡng kiểm tra cơ bản."})}else checks.push({name:"Content completeness",status:"PASS",detail:"Có nội dung để kiểm tra."});const status=violations.length?"FAIL":"PASS";const score=Math.max(0,1-(violations.length*.25)-(warnings.length*.05));return {status,score,violations,warnings,checks,checkedAt:now(),engine:"DTVT-LOCAL-COUNCIL-V3"}}

  async function renderTimeline(){const ws=$("#timelineWorkspace"),events=await all("timeline"),stories=await all("stories"),chapters=await all("chapters");ws.innerHTML=`<div class="so-shell"><div class="so-toolbar"><div><h2 class="so-title">⏳ Timeline Engine</h2><div class="so-sub">Sự kiện được lưu độc lập và liên kết với Story/Chapter.</div></div><div class="actions"><button class="so-btn primary" id="tlNew">+ Sự kiện</button><button class="so-btn" id="tlExport">Xuất Timeline</button></div></div><div class="so-card pad"><table class="so-table"><thead><tr><th>Thời gian</th><th>Sự kiện</th><th>Truyện</th><th>Chương</th><th>Hệ quả</th></tr></thead><tbody>${events.sort((a,b)=>String(a.time?.sortKey||a.createdAt).localeCompare(String(b.time?.sortKey||b.createdAt))).map(e=>{const s=stories.find(x=>x.id===e.storyId);const c=chapters.find(x=>x.id===e.chapterId);return `<tr><td>${esc(e.time?.label||"—")}</td><td><strong>${esc(e.title)}</strong><div class="so-muted">${esc(e.description||"")}</div></td><td>${esc(s?.title||e.storyId||"—")}</td><td>${c?c.number:"—"}</td><td>${esc(e.consequences||"—")}</td></tr>`}).join("")||`<tr><td colspan="5"><div class="so-empty">Chưa có sự kiện.</div></td></tr>`}</tbody></table></div></div>`;$("#tlNew").onclick=()=>openTimelineModal();$("#tlExport").onclick=exportTimeline}

  async function renderCouncil(){const ws=$("#councilWorkspace"),reports=await all("reports"),chapters=await all("chapters");ws.innerHTML=`<div class="so-shell"><div class="so-toolbar"><div><h2 class="so-title">🤖 Council — Local Validation</h2><div class="so-sub">V3 chuẩn bị interface cho Provider Orchestrator. Chưa chứa API key.</div></div><div class="actions"><button class="so-btn" id="coExport">Xuất Reports</button></div></div><div class="so-grid"><main class="so-main"><div class="so-card pad"><div class="so-report">${reports.slice().reverse().map(r=>{const c=chapters.find(x=>x.id===r.chapterId);return `<div class="so-check ${r.status==="PASS"?"ok":"fail"}"><strong>${r.status} · ${esc(c?.title||r.chapterId)}</strong><span class="so-muted">Score: ${(r.score??0).toFixed(2)} · ${esc(r.engine||"")}</span><div>${(r.violations||[]).map(x=>`<div class="so-danger-text">✕ ${esc(x)}</div>`).join("")}${(r.warnings||[]).map(x=>`<div class="so-muted">⚠ ${esc(x)}</div>`).join("")}</div></div>`}).join("")||`<div class="so-empty">Chưa có báo cáo Council.</div>`}</div></div></main><aside class="so-card pad"><div class="so-title">Pipeline</div><div class="so-list"><div class="so-list-item">1. Context Builder<small>Canon + Story State + Timeline</small></div><div class="so-list-item">2. Provider Selection<small>Interface sẵn sàng cho V4</small></div><div class="so-list-item">3. Council Modules<small>Canon · Logic · Continuity · Character · Power</small></div><div class="so-list-item">4. Decision Protocol<small>Evidence → Risk → Recommendation</small></div></div></aside></div></div>`;$("#coExport").onclick=exportReports}

  async function openStoryModal(existing){const modal=document.createElement("div");modal.className="so-modal";modal.innerHTML=`<div class="so-modal-box"><h3>${existing?"Sửa truyện":"Tạo truyện mới"}</h3><div class="so-form"><label>Tên truyện</label><input id="mTitle" value="${esc(existing?.title||"")}"/><label>Mô tả</label><textarea id="mDesc">${esc(existing?.description||"")}</textarea><label>Canon Version</label><input id="mCanon" value="${esc(existing?.canonVersion||"LIVE")}"/><label>Canon IDs nền tảng (mỗi dòng một ID)</label><textarea id="mRefs" style="min-height:130px">${esc((existing?.canonRefs||[]).join("\n"))}</textarea></div><div class="so-modal-actions"><button class="so-btn" id="mCancel">Hủy</button><button class="so-btn primary" id="mSave">Lưu</button></div></div>`;document.body.appendChild(modal);$("#mCancel").onclick=()=>modal.remove();$("#mSave").onclick=async()=>{const title=$("#mTitle").value.trim();if(!title){alert("Nhập tên truyện.");return}const s=existing?{...existing,title,description:$("#mDesc").value.trim(),canonVersion:$("#mCanon").value.trim()||"LIVE",canonRefs:lines($("#mRefs").value),updatedAt:now()}:({...baseStory(),title,description:$("#mDesc").value.trim(),canonVersion:$("#mCanon").value.trim()||"LIVE",canonRefs:lines($("#mRefs").value)});await put("stories",s);currentStory=s;modal.remove();renderStory()}}

  async function openTimelineModal(){const stories=await all("stories"),chapters=await all("chapters");const modal=document.createElement("div");modal.className="so-modal";modal.innerHTML=`<div class="so-modal-box"><h3>Thêm sự kiện Timeline</h3><div class="so-form"><label>Truyện</label><select id="tStory">${stories.map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join("")}</select><label>Chương</label><select id="tChapter"><option value="">Không liên kết</option>${chapters.map(c=>`<option value="${c.id}">${c.number}. ${esc(c.title)}</option>`).join("")}</select><label>Nhãn thời gian</label><input id="tTime" placeholder="Ví dụ: Kỷ nguyên 7 · Năm 1204"/><label>Tiêu đề</label><input id="tTitle"/><label>Mô tả</label><textarea id="tDesc"></textarea><label>Hệ quả</label><textarea id="tCons"></textarea></div><div class="so-modal-actions"><button class="so-btn" id="tCancel">Hủy</button><button class="so-btn primary" id="tSave">Lưu</button></div></div>`;document.body.appendChild(modal);$("#tCancel").onclick=()=>modal.remove();$("#tSave").onclick=async()=>{const e={id:uid("event"),storyId:$("#tStory").value,chapterId:$("#tChapter").value||null,time:{label:$("#tTime").value,sortKey:$("#tTime").value},title:$("#tTitle").value.trim()||"Sự kiện mới",description:$("#tDesc").value.trim(),consequences:$("#tCons").value.trim(),createdAt:now()};await put("timeline",e);modal.remove();renderTimeline()}}

  async function exportStore(store,name){const data=await all(store);const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  async function exportStory(){const [stories,chapters,timeline,proposals,reports]=await Promise.all(STORES.map(all));const payload={schema:"DTVT-STORY-OS-V3",exportedAt:now(),stories,chapters,timeline,proposals,reports};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`dtvt-story-os-v3-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  async function importStory(file){try{const data=JSON.parse(await file.text());if(data.schema!=="DTVT-STORY-OS-V3")throw new Error("Không đúng schema DTVT Story OS V3.");for(const s of STORES)if(Array.isArray(data[s]))await bulk(s,data[s]);currentStory=(data.stories||[])[0]||null;currentChapter=null;alert("Đã nhập Story OS V3.");renderStory()}catch(e){alert("Nhập Story thất bại: "+e.message)}}
  function exportTimeline(){exportStore("timeline",`dtvt-timeline-${new Date().toISOString().slice(0,10)}.json`)}
  function exportReports(){exportStore("reports",`dtvt-council-reports-${new Date().toISOString().slice(0,10)}.json`)}

  function boot(){["Canon","Story","Timeline","Council"].forEach(m=>{const b=$("#mode"+m);if(b)b.onclick=()=>setMode(m.toLowerCase())});setMode("canon");}
  window.addEventListener("DOMContentLoaded",boot);
  window.DTVT_STORY_OS_V3={openDB,all,get,put,remove,canonEntries,validateChapter,renderStory};
})();
